name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
        image: blang/latex

    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Install inkscape and make
        run: |
          apt update
          apt install --yes inkscape make
      - name: Build Slides
        run: |
          make slides
      - name: Build Handout
        run: |
          make handout
      - name: Create Release
        if: startsWith(github.event.ref, 'refs/tags')
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref_name }}
          artifacts: "GitWorkshop_Slides.pdf,GitWorkshop_Handout.pdf"
          generateReleaseNotes: true
